/**
 * Visual trait configurations for all 135 Israeli politicians.
 * Used by AvatarGenerator.jsx to render distinctive SVG avatars.
 *
 * Traits: skin, face, hair, hairColor, grayHair, eyeColor, glasses,
 *         beard, beardColor, headCovering, suitColor, tieColor, bgColor,
 *         eyebrowThick
 *
 * Skin tones: light=#f0d0b4, medium=#e8c8a8, olive=#d4b896, dark=#8b6b4a, ethiopian=#6b4a2a
 * Hair: swept, short, curly, receding, bald, long, styled, side-part
 * Glasses: round, rectangular, thin, null
 * Beard: full, goatee, stubble, mustache, null
 * Head covering: kippah, kippah-white, kippah-knit, shtreimel, hijab, null
 */

// Female politicians (no beard, longer hair options, no tie by default)
const F = { beard: null, tieColor: null };
// Haredi politicians (typically black suit, beard, kippah/shtreimel)
const H = { suitColor: "#0a0a0a", tieColor: null };
// Religious (kippah)
const R = { headCovering: "kippah" };

const POLITICIAN_TRAITS = {
  // ── Likud ───────────────────────────────────────────────────────────
  "benjamin-netanyahu": null, // Keep original hand-crafted
  "yariv-levin": {
    hair: "receding",
    hairColor: "#4a4a4a",
    grayHair: true,
    face: "long",
    glasses: "rectangular",
    suitColor: "#1a1a2e",
    tieColor: "#8e44ad",
  },
  "nir-barkat": {
    hair: "short",
    hairColor: "#3a3a3a",
    grayHair: true,
    face: "square",
    eyeColor: "#4a6741",
    suitColor: "#1a1a2e",
    tieColor: "#2980b9",
  },
  "amir-ohana": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "round",
    eyeColor: "#3d2b1f",
    suitColor: "#2c3e50",
    tieColor: "#c0392b",
  },
  "yisrael-katz": {
    hair: "receding",
    hairColor: "#555",
    grayHair: true,
    face: "round",
    glasses: "rectangular",
    suitColor: "#1a1a2e",
    tieColor: "#c0392b",
  },
  "yuli-edelstein": {
    hair: "swept",
    hairColor: "#888",
    grayHair: true,
    face: "oval",
    eyeColor: "#4a6741",
    suitColor: "#2c3e50",
    tieColor: "#2980b9",
  },
  "shlomo-karhi": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "round",
    headCovering: "kippah",
    suitColor: "#1a1a2e",
    tieColor: "#e74c3c",
  },
  "avi-dichter": {
    hair: "short",
    hairColor: "#777",
    grayHair: true,
    face: "square",
    suitColor: "#1a1a2e",
    tieColor: "#2c3e50",
  },
  "david-bitan": {
    hair: "receding",
    hairColor: "#555",
    grayHair: true,
    face: "round",
    eyebrowThick: true,
    suitColor: "#1a1a2e",
    tieColor: "#c0392b",
  },
  "boaz-bismuth": {
    hair: "styled",
    hairColor: "#3a3a3a",
    face: "oval",
    glasses: "thin",
    suitColor: "#2c3e50",
    tieColor: "#8e44ad",
  },
  "ariel-kallner": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    suitColor: "#1a1a2e",
    tieColor: "#2980b9",
  },
  "hanoch-milwidsky": {
    hair: "receding",
    hairColor: "#888",
    grayHair: true,
    face: "round",
    eyebrowThick: true,
    suitColor: "#1a1a2e",
    tieColor: "#c0392b",
  },
  "tally-gotliv": {
    ...F,
    hair: "long",
    hairColor: "#8b6914",
    face: "oval",
    skin: "#f0d0b4",
    suitColor: "#2c3e50",
  },
  "dan-ilouz": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    beard: "stubble",
    beardColor: "#2c2c2c",
    suitColor: "#1a1a2e",
    tieColor: "#c0392b",
  },
  "moshe-saada": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "round",
    skin: "#e8c8a8",
    suitColor: "#1a1a2e",
    tieColor: "#e74c3c",
  },
  "nissim-vaturi": {
    hair: "short",
    hairColor: "#3a3a3a",
    face: "round",
    skin: "#e8c8a8",
    suitColor: "#2c3e50",
    tieColor: "#c0392b",
  },
  "osher-shkalim": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    skin: "#e8c8a8",
    suitColor: "#1a1a2e",
    tieColor: "#2980b9",
  },
  "avichay-buaron": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "square",
    suitColor: "#1a1a2e",
    tieColor: "#8e44ad",
  },
  "tsega-melaku": {
    hair: "short",
    hairColor: "#1a1a1a",
    face: "oval",
    skin: "#6b4a2a",
    eyeColor: "#1a1a1a",
    suitColor: "#1a1a2e",
    tieColor: "#2980b9",
  },
  "eliyahu-revivo": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "round",
    skin: "#e8c8a8",
    suitColor: "#2c3e50",
    tieColor: "#c0392b",
  },
  "keti-shitrit": {
    ...F,
    hair: "long",
    hairColor: "#2c2c2c",
    face: "oval",
    skin: "#e8c8a8",
    suitColor: "#8e44ad",
  },
  "ofir-katz": {
    hair: "short",
    hairColor: "#3a3a3a",
    face: "square",
    suitColor: "#1a1a2e",
    tieColor: "#c0392b",
  },
  "may-golan": {
    ...F,
    hair: "long",
    hairColor: "#d4a029",
    face: "oval",
    eyeColor: "#4a6741",
    suitColor: "#2c3e50",
  },
  "gila-gamliel": {
    ...F,
    hair: "styled",
    hairColor: "#5a3a2a",
    face: "round",
    skin: "#e8c8a8",
    suitColor: "#8e44ad",
  },
  "galit-distel-atbaryan": {
    ...F,
    hair: "long",
    hairColor: "#c87020",
    face: "oval",
    suitColor: "#c0392b",
  },
  "eli-dalal": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    skin: "#e8c8a8",
    suitColor: "#1a1a2e",
    tieColor: "#2980b9",
  },
  "shalom-danino": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "round",
    skin: "#e8c8a8",
    suitColor: "#2c3e50",
    tieColor: "#c0392b",
  },
  "amit-halevi": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "square",
    headCovering: "kippah",
    suitColor: "#1a1a2e",
    tieColor: "#e74c3c",
  },
  "hava-eti-atia": {
    ...F,
    hair: "styled",
    hairColor: "#2c2c2c",
    face: "round",
    skin: "#e8c8a8",
    suitColor: "#2c3e50",
  },
  "moshe-passal": {
    hair: "short",
    hairColor: "#555",
    grayHair: true,
    face: "round",
    suitColor: "#1a1a2e",
    tieColor: "#2980b9",
  },
  "sasson-guetta": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "round",
    skin: "#e8c8a8",
    suitColor: "#2c3e50",
    tieColor: "#c0392b",
  },
  "afif-abed": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    skin: "#d4b896",
    beard: "mustache",
    beardColor: "#2c2c2c",
    suitColor: "#1a1a2e",
    tieColor: "#2980b9",
  },
  "eli-cohen": {
    hair: "styled",
    hairColor: "#3a3a3a",
    grayHair: true,
    face: "oval",
    suitColor: "#1a1a2e",
    tieColor: "#2980b9",
  },
  "david-amsalem": {
    hair: "receding",
    hairColor: "#555",
    grayHair: true,
    face: "round",
    skin: "#e8c8a8",
    suitColor: "#1a1a2e",
    tieColor: "#c0392b",
  },
  "miki-zohar": {
    hair: "styled",
    hairColor: "#2c2c2c",
    face: "oval",
    beard: "stubble",
    beardColor: "#2c2c2c",
    suitColor: "#2c3e50",
    tieColor: "#c0392b",
  },
  "yoav-kish": {
    hair: "short",
    hairColor: "#3a3a3a",
    face: "square",
    suitColor: "#1a1a2e",
    tieColor: "#2980b9",
  },
  "haim-katz": {
    hair: "swept",
    hairColor: "#999",
    grayHair: true,
    face: "round",
    glasses: "rectangular",
    suitColor: "#1a1a2e",
    tieColor: "#c0392b",
  },
  "miri-regev": {
    ...F,
    hair: "styled",
    hairColor: "#5a3a2a",
    face: "round",
    eyeColor: "#3d2b1f",
    suitColor: "#c0392b",
  },
  "amichai-shikli": {
    hair: "short",
    hairColor: "#3a3a3a",
    face: "oval",
    headCovering: "kippah",
    suitColor: "#1a1a2e",
    tieColor: "#2980b9",
  },
  "idit-silman": { ...F, hair: "long", hairColor: "#5a3a2a", face: "oval", suitColor: "#2c3e50" },
  "gideon-saar": {
    hair: "receding",
    hairColor: "#555",
    grayHair: true,
    face: "square",
    suitColor: "#1a1a2e",
    tieColor: "#8e44ad",
  },
  "zeev-elkin": {
    hair: "receding",
    hairColor: "#555",
    grayHair: true,
    face: "oval",
    glasses: "rectangular",
    suitColor: "#2c3e50",
    tieColor: "#c0392b",
  },

  // ── Yesh Atid ───────────────────────────────────────────────────────
  "yair-lapid": null, // Keep original hand-crafted
  "boaz-toporovsky": {
    hair: "receding",
    hairColor: "#555",
    grayHair: true,
    face: "oval",
    glasses: "thin",
    suitColor: "#2c3e50",
    tieColor: "#f59e0b",
  },
  "meir-cohen": {
    hair: "bald",
    face: "round",
    skin: "#e8c8a8",
    grayHair: true,
    suitColor: "#1a1a2e",
    tieColor: "#f59e0b",
  },
  "karine-elharrar": {
    ...F,
    hair: "styled",
    hairColor: "#5a3a2a",
    face: "oval",
    glasses: "round",
    suitColor: "#2c3e50",
  },
  "mickey-levy": {
    hair: "bald",
    face: "round",
    grayHair: true,
    glasses: "thin",
    suitColor: "#1a1a2e",
    tieColor: "#f59e0b",
  },
  "yorai-lahav-hertzano": {
    hair: "curly",
    hairColor: "#3a3a3a",
    face: "oval",
    suitColor: "#2c3e50",
    tieColor: "#f59e0b",
  },
  "meirav-ben-ari": {
    ...F,
    hair: "long",
    hairColor: "#2c2c2c",
    face: "oval",
    suitColor: "#8e44ad",
  },
  "ron-katz": {
    hair: "short",
    hairColor: "#3a3a3a",
    face: "square",
    suitColor: "#2c3e50",
    tieColor: "#f59e0b",
  },
  "simon-davidson": {
    hair: "short",
    hairColor: "#555",
    grayHair: true,
    face: "oval",
    suitColor: "#1a1a2e",
    tieColor: "#f59e0b",
  },
  "debbie-biton": {
    ...F,
    hair: "long",
    hairColor: "#8b6914",
    face: "round",
    skin: "#e8c8a8",
    suitColor: "#2c3e50",
  },
  "naor-shiri": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    beard: "stubble",
    beardColor: "#2c2c2c",
    suitColor: "#2c3e50",
    tieColor: "#f59e0b",
  },
  "merav-cohen": { ...F, hair: "styled", hairColor: "#5a3a2a", face: "oval", suitColor: "#2c3e50" },
  "tatiana-mazarsky": {
    ...F,
    hair: "long",
    hairColor: "#d4a029",
    face: "oval",
    eyeColor: "#2c5f8a",
    suitColor: "#2c3e50",
  },
  "vladimir-beliak": {
    hair: "short",
    hairColor: "#4a3a2a",
    face: "square",
    suitColor: "#2c3e50",
    tieColor: "#f59e0b",
  },
  "moshe-tur-paz": {
    hair: "short",
    hairColor: "#555",
    grayHair: true,
    face: "oval",
    headCovering: "kippah",
    suitColor: "#1a1a2e",
    tieColor: "#f59e0b",
  },
  "yoav-segalovitz": {
    hair: "receding",
    hairColor: "#555",
    grayHair: true,
    face: "oval",
    suitColor: "#2c3e50",
    tieColor: "#f59e0b",
  },
  "elazar-stern": {
    hair: "bald",
    face: "round",
    grayHair: true,
    headCovering: "kippah",
    suitColor: "#1a1a2e",
    tieColor: "#f59e0b",
  },
  "ram-ben-barak": {
    hair: "short",
    hairColor: "#777",
    grayHair: true,
    face: "square",
    suitColor: "#1a1a2e",
    tieColor: "#2980b9",
  },
  "yaron-levy": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    suitColor: "#2c3e50",
    tieColor: "#f59e0b",
  },
  "shelly-tal-meron": {
    ...F,
    hair: "styled",
    hairColor: "#8b6914",
    face: "oval",
    suitColor: "#2c3e50",
  },
  "adi-azuz": {
    ...F,
    hair: "long",
    hairColor: "#2c2c2c",
    face: "oval",
    skin: "#e8c8a8",
    suitColor: "#2c3e50",
  },
  "yasmin-fridman": {
    ...F,
    hair: "long",
    hairColor: "#5a3a2a",
    face: "round",
    suitColor: "#8e44ad",
  },
  "matti-sarfatti-harcavi": {
    hair: "short",
    hairColor: "#555",
    grayHair: true,
    face: "oval",
    glasses: "thin",
    suitColor: "#2c3e50",
    tieColor: "#f59e0b",
  },
  "michal-shir-segman": {
    ...F,
    hair: "long",
    hairColor: "#2c2c2c",
    face: "oval",
    suitColor: "#2c3e50",
  },

  // ── Blue and White ──────────────────────────────────────────────────
  "benny-gantz": null, // Keep original hand-crafted
  "pnina-tamano-shata": {
    ...F,
    hair: "curly",
    hairColor: "#1a1a1a",
    face: "round",
    skin: "#6b4a2a",
    eyeColor: "#1a1a1a",
    suitColor: "#2c3e50",
  },
  "hili-tropper": {
    hair: "short",
    hairColor: "#3a3a3a",
    face: "oval",
    suitColor: "#2c3e50",
    tieColor: "#2980b9",
  },
  "orit-farkash-hacohen": {
    ...F,
    hair: "styled",
    hairColor: "#5a3a2a",
    face: "oval",
    glasses: "thin",
    suitColor: "#2c3e50",
  },
  "alon-schuster": {
    hair: "swept",
    hairColor: "#888",
    grayHair: true,
    face: "oval",
    suitColor: "#1a1a2e",
    tieColor: "#2980b9",
  },
  "michael-biton": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "round",
    skin: "#e8c8a8",
    suitColor: "#1a1a2e",
    tieColor: "#2980b9",
  },
  "eitan-ginzburg": {
    hair: "short",
    hairColor: "#4a3a2a",
    face: "oval",
    suitColor: "#2c3e50",
    tieColor: "#2980b9",
  },
  "yael-ron-ben-moshe": {
    ...F,
    hair: "styled",
    hairColor: "#5a3a2a",
    face: "oval",
    suitColor: "#2c3e50",
  },

  // ── Yashar ──────────────────────────────────────────────────────────
  "gadi-eisenkot": {
    hair: "short",
    hairColor: "#777",
    grayHair: true,
    face: "square",
    suitColor: "#1a1a2e",
    tieColor: "#2c3e50",
  },
  "matan-kahana": {
    hair: "short",
    hairColor: "#4a3a2a",
    face: "oval",
    ...R,
    suitColor: "#1a1a2e",
    tieColor: "#2980b9",
  },

  // ── HaMiluimnikim ───────────────────────────────────────────────────
  "yoaz-hendel": {
    hair: "short",
    hairColor: "#555",
    grayHair: true,
    face: "square",
    glasses: "rectangular",
    suitColor: "#2c3e50",
    tieColor: "#2980b9",
  },

  // ── Shas ────────────────────────────────────────────────────────────
  "aryeh-deri": {
    ...H,
    hair: "receding",
    hairColor: "#2c2c2c",
    face: "round",
    headCovering: "kippah",
    beard: "stubble",
    beardColor: "#2c2c2c",
    glasses: "rectangular",
  },
  "yoav-ben-tzur": {
    ...H,
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    headCovering: "kippah",
    beard: "stubble",
    beardColor: "#2c2c2c",
  },
  "yinon-azoulay": {
    ...H,
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    headCovering: "kippah",
    beard: "full",
    beardColor: "#2c2c2c",
  },
  "moshe-arbel": {
    ...H,
    hair: "short",
    hairColor: "#2c2c2c",
    face: "round",
    headCovering: "kippah",
    beard: "full",
    beardColor: "#2c2c2c",
    glasses: "rectangular",
  },
  "michael-malchieli": {
    ...H,
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    headCovering: "kippah",
    beard: "goatee",
    beardColor: "#2c2c2c",
  },
  "haim-biton": {
    ...H,
    hair: "short",
    hairColor: "#555",
    grayHair: true,
    face: "round",
    headCovering: "kippah",
  },
  "uriel-buso": {
    ...H,
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    headCovering: "kippah",
    skin: "#e8c8a8",
  },
  "yaakov-margi": {
    ...H,
    hair: "receding",
    hairColor: "#555",
    grayHair: true,
    face: "round",
    headCovering: "kippah",
    beard: "stubble",
    beardColor: "#555",
    glasses: "rectangular",
  },
  "moshe-abutbul": {
    ...H,
    hair: "short",
    hairColor: "#2c2c2c",
    face: "round",
    headCovering: "kippah",
    beard: "full",
    beardColor: "#2c2c2c",
    skin: "#e8c8a8",
  },
  "yosef-taieb": {
    ...H,
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    headCovering: "kippah",
    beard: "goatee",
    beardColor: "#2c2c2c",
    skin: "#e8c8a8",
  },
  "yonatan-mishraki": {
    ...H,
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    headCovering: "kippah",
    beard: "stubble",
    beardColor: "#2c2c2c",
  },

  // ── United Torah Judaism ────────────────────────────────────────────
  "yitzhak-goldknopf": {
    ...H,
    hair: "receding",
    hairColor: "#555",
    grayHair: true,
    face: "round",
    headCovering: "shtreimel",
    beard: "full",
    beardColor: "#555",
    glasses: "round",
  },
  "moshe-gafni": {
    ...H,
    hair: "receding",
    hairColor: "#888",
    grayHair: true,
    face: "round",
    headCovering: "kippah",
    beard: "stubble",
    beardColor: "#888",
    glasses: "rectangular",
  },
  "uri-maklev": {
    ...H,
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    headCovering: "kippah",
    beard: "full",
    beardColor: "#2c2c2c",
  },
  "yaakov-tesler": {
    ...H,
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    headCovering: "kippah",
    beard: "goatee",
    beardColor: "#2c2c2c",
  },
  "meir-porush": {
    ...H,
    hair: "receding",
    hairColor: "#888",
    grayHair: true,
    face: "round",
    headCovering: "shtreimel",
    beard: "full",
    beardColor: "#888",
    glasses: "round",
  },
  "yaakov-asher": {
    ...H,
    hair: "short",
    hairColor: "#555",
    grayHair: true,
    face: "round",
    headCovering: "kippah",
    beard: "full",
    beardColor: "#555",
    glasses: "rectangular",
  },
  "yitzhak-pindrus": {
    ...H,
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    headCovering: "kippah",
    beard: "full",
    beardColor: "#2c2c2c",
    glasses: "round",
  },

  // ── Religious Zionism ───────────────────────────────────────────────
  "bezalel-smotrich": null, // Keep original hand-crafted
  "orit-strock": {
    ...F,
    hair: "long",
    hairColor: "#8b6914",
    face: "oval",
    headCovering: "kippah-knit",
    suitColor: "#2c3e50",
  },
  "ofir-sofer": {
    hair: "short",
    hairColor: "#4a3a2a",
    face: "oval",
    ...R,
    beard: "stubble",
    beardColor: "#4a3a2a",
    suitColor: "#1a1a2e",
    tieColor: "#e74c3c",
  },
  "simcha-rothman": {
    hair: "short",
    hairColor: "#3a3a3a",
    face: "oval",
    ...R,
    beard: "goatee",
    beardColor: "#3a3a3a",
    glasses: "rectangular",
    suitColor: "#1a1a2e",
    tieColor: "#c0392b",
  },
  "zvi-sukkot": {
    hair: "curly",
    hairColor: "#4a3a2a",
    face: "oval",
    ...R,
    beard: "full",
    beardColor: "#4a3a2a",
    suitColor: "white",
    tieColor: null,
  },
  "ohad-tal": {
    hair: "short",
    hairColor: "#4a3a2a",
    face: "square",
    ...R,
    beard: "stubble",
    beardColor: "#4a3a2a",
    suitColor: "#1a1a2e",
    tieColor: "#e74c3c",
  },
  "michal-waldiger": {
    ...F,
    hair: "long",
    hairColor: "#5a3a2a",
    face: "oval",
    suitColor: "#2c3e50",
  },
  "moshe-solomon": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    ...R,
    beard: "goatee",
    beardColor: "#2c2c2c",
    suitColor: "#1a1a2e",
    tieColor: "#c0392b",
  },

  // ── Otzma Yehudit ───────────────────────────────────────────────────
  "itamar-ben-gvir": {
    hair: "receding",
    hairColor: "#c87020",
    face: "round",
    ...R,
    suitColor: "#1a1a2e",
    tieColor: "#e74c3c",
    eyebrowThick: true,
  },
  "zvika-fogel": {
    hair: "short",
    hairColor: "#777",
    grayHair: true,
    face: "square",
    suitColor: "#1a1a2e",
    tieColor: "#c0392b",
  },
  "yitzhak-wasserlauf": {
    hair: "short",
    hairColor: "#3a3a3a",
    face: "oval",
    ...R,
    beard: "stubble",
    beardColor: "#3a3a3a",
    suitColor: "#1a1a2e",
    tieColor: "#e74c3c",
  },
  "amichai-eliyahu": {
    hair: "curly",
    hairColor: "#4a3a2a",
    face: "round",
    ...R,
    beard: "goatee",
    beardColor: "#4a3a2a",
    suitColor: "#1a1a2e",
    tieColor: "#c0392b",
  },
  "limor-son-har-melech": {
    ...F,
    hair: "long",
    hairColor: "#5a3a2a",
    face: "oval",
    headCovering: "kippah-knit",
    suitColor: "#c0392b",
  },
  "yitzhak-kroizer": {
    hair: "curly",
    hairColor: "#4a3a2a",
    face: "oval",
    ...R,
    beard: "full",
    beardColor: "#4a3a2a",
    suitColor: "white",
    tieColor: null,
  },

  // ── Yisrael Beiteinu ────────────────────────────────────────────────
  "avigdor-lieberman": null, // Keep original hand-crafted
  "oded-forer": {
    hair: "short",
    hairColor: "#3a3a3a",
    face: "oval",
    suitColor: "#2c3e50",
    tieColor: "#2980b9",
  },
  "evgeny-sova": {
    hair: "short",
    hairColor: "#4a3a2a",
    face: "square",
    suitColor: "#1a1a2e",
    tieColor: "#2980b9",
  },
  "hamad-amar": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "round",
    skin: "#d4b896",
    beard: "mustache",
    beardColor: "#2c2c2c",
    suitColor: "#1a1a2e",
    tieColor: "#2980b9",
  },
  "yulia-malinovsky": {
    ...F,
    hair: "long",
    hairColor: "#d4a029",
    face: "oval",
    eyeColor: "#2c5f8a",
    suitColor: "#2c3e50",
  },
  "sharon-nir": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    suitColor: "#2c3e50",
    tieColor: "#2980b9",
  },

  // ── Ra'am ───────────────────────────────────────────────────────────
  "mansour-abbas": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "round",
    skin: "#d4b896",
    beard: "mustache",
    beardColor: "#2c2c2c",
    glasses: "rectangular",
    suitColor: "#1a1a2e",
    tieColor: "#27ae60",
  },
  "waleed-taha": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    skin: "#d4b896",
    beard: "full",
    beardColor: "#2c2c2c",
    suitColor: "#1a1a2e",
    tieColor: "#27ae60",
  },
  "iman-khatib-yasin": {
    ...F,
    hair: "long",
    hairColor: "#2c2c2c",
    face: "oval",
    skin: "#d4b896",
    headCovering: "hijab",
    suitColor: "#2c3e50",
  },
  "walid-alhawashla": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "round",
    skin: "#d4b896",
    beard: "stubble",
    beardColor: "#2c2c2c",
    suitColor: "#1a1a2e",
    tieColor: "#27ae60",
  },
  "yasser-hujirat": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    skin: "#d4b896",
    beard: "goatee",
    beardColor: "#2c2c2c",
    suitColor: "#2c3e50",
    tieColor: "#27ae60",
  },

  // ── Hadash-Ta'al ────────────────────────────────────────────────────
  "ayman-odeh": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    skin: "#d4b896",
    beard: "stubble",
    beardColor: "#2c2c2c",
    suitColor: "#2c3e50",
    tieColor: "#c0392b",
  },
  "ahmad-tibi": {
    hair: "receding",
    hairColor: "#555",
    grayHair: true,
    face: "round",
    skin: "#d4b896",
    beard: "mustache",
    beardColor: "#555",
    glasses: "thin",
    suitColor: "#1a1a2e",
    tieColor: "#c0392b",
  },
  "aida-touma-suleiman": {
    ...F,
    hair: "short",
    hairColor: "#2c2c2c",
    face: "round",
    skin: "#d4b896",
    glasses: "round",
    suitColor: "#c0392b",
  },
  "ofer-cassif": {
    hair: "receding",
    hairColor: "#888",
    grayHair: true,
    face: "oval",
    glasses: "round",
    suitColor: "#2c3e50",
    tieColor: "#c0392b",
  },
  "samir-ben-said": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    skin: "#d4b896",
    suitColor: "#1a1a2e",
    tieColor: "#c0392b",
  },

  // ── Democrats ───────────────────────────────────────────────────────
  "naama-lazimi": { ...F, hair: "long", hairColor: "#5a3a2a", face: "oval", suitColor: "#e74c3c" },
  "gilad-kariv": {
    hair: "receding",
    hairColor: "#555",
    grayHair: true,
    face: "oval",
    headCovering: "kippah",
    glasses: "rectangular",
    suitColor: "#2c3e50",
    tieColor: "#e74c3c",
  },
  "efrat-rayten": {
    ...F,
    hair: "styled",
    hairColor: "#5a3a2a",
    face: "round",
    suitColor: "#2c3e50",
  },
  "yair-golan": {
    hair: "short",
    hairColor: "#777",
    grayHair: true,
    face: "square",
    suitColor: "#1a1a2e",
    tieColor: "#e74c3c",
  },

  // ── Others ──────────────────────────────────────────────────────────
  "sharren-haskel": {
    ...F,
    hair: "long",
    hairColor: "#2c2c2c",
    face: "oval",
    suitColor: "#2c3e50",
  },
  "michel-buskila": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "round",
    skin: "#e8c8a8",
    suitColor: "#1a1a2e",
    tieColor: "#2980b9",
  },
  "akram-hasson": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "round",
    skin: "#d4b896",
    beard: "mustache",
    beardColor: "#2c2c2c",
    suitColor: "#1a1a2e",
    tieColor: "#2980b9",
  },
  "avi-maoz": {
    hair: "short",
    hairColor: "#3a3a3a",
    face: "oval",
    ...R,
    beard: "full",
    beardColor: "#3a3a3a",
    suitColor: "white",
    tieColor: null,
  },
  "matan-yafe": {
    hair: "short",
    hairColor: "#2c2c2c",
    face: "oval",
    suitColor: "#2c3e50",
    tieColor: "#2980b9",
  },
  "naftali-bennett": {
    hair: "short",
    hairColor: "#4a3a2a",
    face: "square",
    ...R,
    suitColor: "#1a1a2e",
    tieColor: "#27ae60",
  },
};

export default POLITICIAN_TRAITS;
